package com.gigadrivegroup.kotlincommons.util

public const val ALPHANUMERIC_CHARACTERS_UPPERCASE: String = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

public const val ALPHANUMERIC_CHARACTERS_LOWERCASE: String = "abcdefghijklmnopqrstuvwxyz"

public const val ALPHANUMERIC_CHARACTERS_NUMBERS: String = "0123456789"

public val ALPHANUMERIC_CHARACTERS: String =
    ALPHANUMERIC_CHARACTERS_UPPERCASE +
        ALPHANUMERIC_CHARACTERS_LOWERCASE +
        ALPHANUMERIC_CHARACTERS_NUMBERS
